### ISSUE TITLE
Missing ncbi/nametable.tsv

### ISSUE THREAD

**Issue by meret-haeusler** [GuazzaroniLab/nanopore_ICU_profiling#3]
Hi,

I am currently working on a project where we re-create your workflow.

Unfortunately, we are not able to find the ncbi/nametable.tsv file that is needed for running alignment-parser.R, or see where it is created in the python script.

Could you give us a hint on how to get it or provide the file you used?

Cheers,
Meret

**Comment by fmpds** [comment]
Hi, Meret

I just uploaded the missing files. Please, download the folder again and let us know if it worked for you. Let us know if there are remaining issues.

Cheers, Felipe.

**Comment by meret-haeusler** [comment]
Hi Felipe,

now everything works!

Thanks for the quick help,
Meret
